### ISSUE TITLE
Enhanced Rollback Feature

### ISSUE THREAD

**Issue by Matthiee** [MatthiWare/UpdateLib#29]
## TODO
- [ ] - Keep old files so we can rollback at a later stage (if needed)
- [ ] - Extend rollback UI 

## Future
- [ ] - Rollback to any previous version
